export const LOAD_HALL = 'LOAD_HALL';
export const RESERVE_PLACE = 'RESERVE_PLACE';
export const SET_PLACE_EMPTY = 'SET_PLACE_EMPTY';

export const OCCUPY_PLACES = 'OCCUPY_PLACES';

export const ADD_PLACE_TO_ORDER = 'ADD_PLACE_TO_ORDER';
export const REMOVE_PLACE_FROM_ORDER = 'REMOVE_PLACE_FROM_ORDER';
export const CLEAN_ORDER_LIST = 'CLEAN_ORDER_LIST';